### PR TITLE
Added professors and new verbs from Tim's version of this

### PR DESCRIPTION
**Pull request by AndrewGuenther**
Tested it and everything still works.

### CODE REVIEW

**Comment by AndrewGuenther** [comment]
I think if we have a script that we just have to run once by hand every quarter that wouldn't be too bad. Right?

(Thanks, phone number removed.)

**Comment by warpling** [comment]
Yeah, just not as funny since over half of those classes aren't offered every quarter. I think it's better to just do it by hand… or not care about it :P We started building a scraper for RatePoly, but it's on pause…

**Comment by AndrewGuenther** [comment]
Updating a pull request over a year later :sunglasses:

**Comment by warpling** [comment]
( ＾◡＾)っ✂╰⋃╯

**Comment by AndrewGuenther** [comment]
Merge pls.

**Comment by warpling** [comment]
I think in May I was trying to say that you castrated the list?
Merged, sorry this slipped by :P

**Comment by warpling** [comment]
Git, why your buttons so confusing?

**Pull request merged**
